services:
  nginx:
    volumes:
      - ./nginx/nginx_no_ssl.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/certbot/letsencrypt:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/letsencrypt