services:
  nginx:
    volumes:
      - ./nginx/nginx_no_ssl.template.conf:/etc/nginx/templates/default.conf.template
      - ./volumes/certbot/letsencrypt:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/letsencrypt